apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-cicd
spec:
  selector:
    matchLabels:
      app: nextjs-cicd
  replicas: 1
  template:
    metadata:
      labels:
        app: nextjs-cicd
    spec:
      containers:
      - name: nextjs-cicd
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 3001
      restartPolicy: Always